#!/usr/bin/env python3
"""
PowerPoint Generator API Endpoint
Integrates with dashboard to auto-generate PPTs from Gem output
"""

from flask import jsonify, request, send_file
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE
from datetime import datetime
import json
import io
import tempfile


class Colors:
    BLUE = RGBColor(82, 138, 202)
    TEAL = RGBColor(82, 204, 138)
    ORANGE = RGBColor(255, 138, 82)
    PURPLE = RGBColor(138, 82, 204)
    DARK_TEXT = RGBColor(33, 33, 33)
    GRAY_TEXT = RGBColor(102, 102, 102)
    RED = RGBColor(255, 82, 82)
    YELLOW = RGBColor(255, 204, 82)


def add_slide_title(slide, title_text):
    """Add title to slide matching template"""
    title_box = slide.shapes.add_textbox(Inches(0.44), Inches(0.27), Inches(9), Inches(0.82))
    tf = title_box.text_frame
    tf.text = title_text
    p = tf.paragraphs[0]
    p.font.size = Pt(28)
    p.font.bold = True
    p.font.name = 'Helvetica'
    p.font.color.rgb = Colors.DARK_TEXT


def add_insight_box(slide, insight_text):
    """Add insight box at bottom of slide"""
    insight = slide.shapes.add_textbox(Inches(1.23), Inches(0.82), Inches(8.44), Inches(0.51))
    tf = insight.text_frame
    tf.text = f"💡 {insight_text}"
    p = tf.paragraphs[0]
    p.font.size = Pt(11)
    p.font.italic = True
    p.font.color.rgb = Colors.GRAY_TEXT


def generate_ppt_from_gem_code(python_code: str, customer_name: str = "Customer") -> bytes:
    """
    Execute Gem-generated Python code and return PowerPoint bytes

    This is SAFE because:
    1. Code is generated by trusted Gem (not user input)
    2. Executes in isolated scope
    3. Returns bytes directly (no file system access)
    """
    import tempfile
    import os

    # Create temp file to execute code
    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
        f.write(python_code)
        temp_script = f.name

    try:
        # Execute the generated code
        import subprocess
        result = subprocess.run(
            ['python3', temp_script],
            capture_output=True,
            text=True,
            timeout=30
        )

        if result.returncode != 0:
            raise Exception(f"Code execution failed: {result.stderr}")

        # Find generated PPT file (should be in current directory)
        ppt_files = [f for f in os.listdir('.') if f.startswith('Health_Check_') and f.endswith('.pptx')]
        if not ppt_files:
            raise Exception("No PowerPoint file was generated")

        ppt_file = ppt_files[0]

        # Read file to bytes
        with open(ppt_file, 'rb') as f:
            ppt_bytes = f.read()

        # Cleanup
        os.remove(ppt_file)

        return ppt_bytes

    finally:
        # Cleanup temp script
        if os.path.exists(temp_script):
            os.remove(temp_script)


def generate_ppt_from_data(workspace_data: dict) -> bytes:
    """
    Generate PowerPoint directly from workspace data (no Gem needed)
    This bypasses Gem entirely - dashboard calls this directly
    """
    # Extract data
    customer_name = workspace_data.get('workspace_info', {}).get('name', 'Customer')

    # MTU data
    usage = workspace_data.get('usage', {})
    mtus = usage.get('mtus', {})
    mtu_current = mtus.get('users', 0) + mtus.get('anonymous', 0)
    quota = usage.get('billing', {}).get('quota', {})
    mtu_quota = quota.get('trackedObjects', 12000000)
    mtu_percent = f"{(mtu_current / mtu_quota * 100):.1f}%" if mtu_quota > 0 else "N/A"

    # Events data
    sources = workspace_data.get('sources', [])
    all_events = []
    for source in sources:
        schema = source.get('schema') if source else None
        if schema:
            for event in schema.get('events', []):
                all_events.append({
                    'event': event.get('name', 'Unknown'),
                    'volume': event.get('counts', {}).get('allowed', 0)
                })

    # Sort by volume
    top_events = sorted(all_events, key=lambda x: x['volume'], reverse=True)[:10]

    # Source library breakdown
    library_counts = {}
    for source in sources:
        if source and source.get('status') == 'ENABLED':
            metadata = source.get('metadata', {})
            if metadata:
                lib = metadata.get('name', 'Unknown')
                library_counts[lib] = library_counts.get(lib, 0) + 1

    # Destinations
    destinations = workspace_data.get('destinations', [])
    active_dests = len([d for d in destinations if d.get('enabled', True)])

    # Create presentation
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(5.625)

    # Slide 1: Title
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    title = slide.shapes.add_textbox(Inches(0.5), Inches(1.94), Inches(9), Inches(1.84))
    tf = title.text_frame
    tf.text = f"{customer_name}\nTechnical Health Check"
    p = tf.paragraphs[0]
    p.font.size = Pt(36)
    p.font.bold = True

    footer = slide.shapes.add_textbox(Inches(0.34), Inches(4.82), Inches(6), Inches(0.5))
    footer.text = f"Prepared {datetime.now().strftime('%B %d, %Y')} by Segment Professional Services"

    # Slide 2: Limits
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    add_slide_title(slide, "Data: Limits")
    add_insight_box(slide, f"MTU usage at {mtu_percent} of total quota.")

    num_box = slide.shapes.add_textbox(Inches(1.5), Inches(2.0), Inches(3), Inches(1.5))
    tf = num_box.text_frame
    tf.text = mtu_percent
    p = tf.paragraphs[0]
    p.font.size = Pt(80)
    p.font.bold = True
    p.font.color.rgb = Colors.TEAL
    p.alignment = PP_ALIGN.CENTER

    label = slide.shapes.add_textbox(Inches(1.5), Inches(3.5), Inches(3), Inches(0.5))
    label.text = f"{mtu_current:,} / {mtu_quota:,} MTUs"
    label.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER

    # Slide 3: Events
    if top_events:
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        add_slide_title(slide, "Data: Events & Props")
        add_insight_box(slide, f"Top {len(top_events)} events by volume shown.")

        chart_data = CategoryChartData()
        chart_data.categories = [e["event"][:30] for e in top_events]
        chart_data.add_series('Volume', [e["volume"] for e in top_events])

        x, y, cx, cy = Inches(0.5), Inches(1.5), Inches(8.5), Inches(3.5)
        chart = slide.shapes.add_chart(XL_CHART_TYPE.BAR_CLUSTERED, x, y, cx, cy, chart_data).chart
        chart.has_legend = False
        series = chart.series[0]
        series.format.fill.solid()
        series.format.fill.fore_color.rgb = Colors.BLUE

    # Slide 4: Syntax Validation
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    add_slide_title(slide, "Data: Syntax")
    add_insight_box(slide, "Event naming analysis - check for consistency across sources.")

    # Analyze event naming patterns
    naming_issues = []
    if all_events:
        # Check for mixed casing
        snake_case = sum(1 for e in all_events if '_' in e['event'])
        title_case = sum(1 for e in all_events if ' ' in e['event'] and e['event'][0].isupper())
        camel_case = sum(1 for e in all_events if e['event'][0].isupper() and ' ' not in e['event'])

        if snake_case > 0 and title_case > 0:
            naming_issues.append(f"Mixed naming: {snake_case} snake_case, {title_case} Title Case events")

        # Generic names
        generic = [e for e in all_events if e['event'].lower() in ['identify', 'track', 'page', 'screen', 'alias']]
        if generic:
            naming_issues.append(f"{len(generic)} generic event names found")

    # Health score
    health = "Good" if len(naming_issues) == 0 else ("Fair" if len(naming_issues) <= 2 else "Needs Attention")
    health_color = Colors.TEAL if health == "Good" else (Colors.YELLOW if health == "Fair" else Colors.RED)

    health_box = slide.shapes.add_textbox(Inches(1), Inches(1.8), Inches(3), Inches(1))
    hf = health_box.text_frame
    hf.text = f"Health:\n{health}"
    hf.paragraphs[0].font.size = Pt(32)
    hf.paragraphs[0].font.bold = True
    hf.paragraphs[0].font.color.rgb = health_color
    hf.paragraphs[0].alignment = PP_ALIGN.CENTER

    # Issues list
    if naming_issues:
        issues_box = slide.shapes.add_textbox(Inches(4.5), Inches(1.8), Inches(5), Inches(2.5))
        if_frame = issues_box.text_frame
        if_frame.text = "Issues Found:"
        if_frame.paragraphs[0].font.bold = True
        for issue in naming_issues[:3]:
            p = if_frame.add_paragraph()
            p.text = f"• {issue}"
            p.font.size = Pt(12)

    # Slide 5: Source Variety
    if library_counts:
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        add_slide_title(slide, "Stack: Source Variety")

        chart_data = CategoryChartData()
        chart_data.categories = list(library_counts.keys())
        chart_data.add_series('Sources', list(library_counts.values()))

        x, y, cx, cy = Inches(1), Inches(1.8), Inches(6), Inches(3)
        chart = slide.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data
        ).chart
        chart.has_legend = False

        active = slide.shapes.add_textbox(Inches(7.5), Inches(2), Inches(2), Inches(1))
        active.text = str(sum(library_counts.values()))
        active.text_frame.paragraphs[0].font.size = Pt(64)
        active.text_frame.paragraphs[0].font.bold = True
        active.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
        label = active.text_frame.add_paragraph()
        label.text = "Active Sources"
        label.alignment = PP_ALIGN.CENTER

    # Slide 6: Source Volume
    # Count events per source - include ALL sources with events, not just ENABLED
    source_volumes = {}
    for source in sources:
        if source:
            schema = source.get('schema')
            if schema:
                events = schema.get('events', [])
                if events:
                    total = sum(e.get('counts', {}).get('allowed', 0) for e in events)
                    if total > 0:
                        source_volumes[source.get('name', 'Unknown')] = total

    if source_volumes:
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        add_slide_title(slide, "Stack: Source Volume")
        add_insight_box(slide, "Event volume by source shows data collection patterns.")

        # Sort and get top 8
        top_sources_vol = sorted(source_volumes.items(), key=lambda x: x[1], reverse=True)[:8]

        chart_data = CategoryChartData()
        chart_data.categories = [s[0][:25] for s in top_sources_vol]
        chart_data.add_series('Events', [s[1] for s in top_sources_vol])

        x, y, cx, cy = Inches(0.5), Inches(1.5), Inches(8.5), Inches(3.5)
        chart = slide.shapes.add_chart(XL_CHART_TYPE.BAR_CLUSTERED, x, y, cx, cy, chart_data).chart
        chart.has_legend = False
        series = chart.series[0]
        series.format.fill.solid()
        series.format.fill.fore_color.rgb = Colors.TEAL

    # Slide 7: Destination Variety
    # Group destinations by category
    dest_categories = {}
    for dest in destinations:
        if dest and dest.get('enabled', True):
            categories = dest.get('metadata', {}).get('categories', [])
            for cat in categories:
                dest_categories[cat] = dest_categories.get(cat, 0) + 1

    if dest_categories:
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        add_slide_title(slide, "Stack: Destination Variety")
        add_insight_box(slide, "Diverse destination categories enable multiple use cases.")

        chart_data = CategoryChartData()
        chart_data.categories = list(dest_categories.keys())[:8]
        chart_data.add_series('Destinations', [dest_categories[k] for k in list(dest_categories.keys())[:8]])

        x, y, cx, cy = Inches(1), Inches(1.8), Inches(6), Inches(3)
        chart = slide.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data).chart
        chart.has_legend = False

        total_box = slide.shapes.add_textbox(Inches(7.5), Inches(2), Inches(2), Inches(1))
        total_box.text = str(active_dests)
        total_box.text_frame.paragraphs[0].font.size = Pt(64)
        total_box.text_frame.paragraphs[0].font.bold = True
        total_box.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
        label = total_box.text_frame.add_paragraph()
        label.text = "Active Destinations"
        label.alignment = PP_ALIGN.CENTER

    # Slide 8: Source<>Destination Connections
    # Count connections - integrations don't have 'enabled' field, count all
    total_connections = 0
    dest_connection_counts = {}
    for source in sources:
        if source:
            integrations = source.get('integrations', [])
            # Count all integrations (they don't have an 'enabled' field)
            for integration in integrations:
                total_connections += 1
                dest_name = integration.get('name', 'Unknown')
                dest_connection_counts[dest_name] = dest_connection_counts.get(dest_name, 0) + 1

    slide = prs.slides.add_slide(prs.slide_layouts[6])
    add_slide_title(slide, "Stack: Source<>Destination Connections")
    add_insight_box(slide, f"{total_connections} total connections between sources and destinations.")

    # Big number
    conn_box = slide.shapes.add_textbox(Inches(1.5), Inches(2), Inches(2.5), Inches(1.5))
    cf = conn_box.text_frame
    cf.text = str(total_connections)
    cf.paragraphs[0].font.size = Pt(72)
    cf.paragraphs[0].font.bold = True
    cf.paragraphs[0].font.color.rgb = Colors.ORANGE
    cf.paragraphs[0].alignment = PP_ALIGN.CENTER
    label = cf.add_paragraph()
    label.text = "Connections"
    label.font.size = Pt(18)
    label.alignment = PP_ALIGN.CENTER

    # Top destinations chart
    if dest_connection_counts:
        top_dests_conn = sorted(dest_connection_counts.items(), key=lambda x: x[1], reverse=True)[:5]

        chart_data = CategoryChartData()
        chart_data.categories = [d[0][:25] for d in top_dests_conn]
        chart_data.add_series('Sources', [d[1] for d in top_dests_conn])

        x, y, cx, cy = Inches(4.5), Inches(1.8), Inches(5), Inches(3)
        chart = slide.shapes.add_chart(XL_CHART_TYPE.BAR_CLUSTERED, x, y, cx, cy, chart_data).chart
        chart.has_legend = False
        series = chart.series[0]
        series.format.fill.solid()
        series.format.fill.fore_color.rgb = Colors.ORANGE

    # Slide 9: Team Activity
    audit_trail = workspace_data.get('audit_trail', [])
    if audit_trail:
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        add_slide_title(slide, "Team: Active Workspace Users")
        add_insight_box(slide, f"{len(audit_trail)} workspace events in recent activity.")

        # Count unique users
        users = set()
        event_types = {}
        for event in audit_trail:
            subject = event.get('subject')
            if subject and subject.get('user'):
                users.add(subject['user'].get('name', 'Unknown'))

            event_type = event.get('type', 'Unknown')
            event_types[event_type] = event_types.get(event_type, 0) + 1

        # User count
        user_box = slide.shapes.add_textbox(Inches(1), Inches(1.8), Inches(2.5), Inches(1))
        uf = user_box.text_frame
        uf.text = str(len(users))
        uf.paragraphs[0].font.size = Pt(64)
        uf.paragraphs[0].font.bold = True
        uf.paragraphs[0].font.color.rgb = Colors.PURPLE
        uf.paragraphs[0].alignment = PP_ALIGN.CENTER
        label = uf.add_paragraph()
        label.text = "Active Users"
        label.alignment = PP_ALIGN.CENTER

        # Event types
        events_box = slide.shapes.add_textbox(Inches(4), Inches(1.8), Inches(5.5), Inches(3))
        ef = events_box.text_frame
        ef.text = "Recent Activity:"
        ef.paragraphs[0].font.bold = True
        for event_type, count in sorted(event_types.items(), key=lambda x: x[1], reverse=True)[:6]:
            p = ef.add_paragraph()
            p.text = f"• {event_type}: {count}"
            p.font.size = Pt(12)

    # Slide 10: Summary
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    add_slide_title(slide, f"Summary for {customer_name}")

    mtu_status = "HEALTHY" if (mtu_current / mtu_quota) < 0.7 else "NEEDS ATTENTION"
    mtu_color = Colors.TEAL if mtu_status == "HEALTHY" else Colors.YELLOW

    rows = [
        ("Data Limits", mtu_status, mtu_color),
        ("Source Variety", "HEALTHY", Colors.TEAL),
        ("Active Destinations", f"{active_dests} destinations", Colors.TEAL),
    ]

    for i, (metric, status, color) in enumerate(rows):
        box = slide.shapes.add_textbox(Inches(1), Inches(1.5 + (i*0.8)), Inches(8), Inches(0.5))
        tf = box.text_frame
        tf.text = f"• {metric}: {status}"
        tf.paragraphs[0].font.color.rgb = color
        tf.paragraphs[0].font.bold = True

    # Slide 11: Conclusions
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    add_slide_title(slide, f"Conclusions for {customer_name}")

    # Three columns
    columns = [
        ("Biggest Issues", [
            "Review data quality",
            "Optimize connections",
            "Update tracking plans"
        ]),
        ("Possible Causes", [
            "Multiple teams",
            "Legacy integrations",
            "Rapid growth"
        ]),
        ("How to Address", [
            "Implement governance",
            "Audit quarterly",
            "Use Protocols"
        ])
    ]

    x_positions = [Inches(0.5), Inches(3.5), Inches(6.5)]

    for idx, (title, items) in enumerate(columns):
        # Column title
        title_box = slide.shapes.add_textbox(x_positions[idx], Inches(1.5), Inches(2.8), Inches(0.4))
        tf = title_box.text_frame
        tf.text = title
        tf.paragraphs[0].font.size = Pt(14)
        tf.paragraphs[0].font.bold = True
        tf.paragraphs[0].font.color.rgb = Colors.BLUE

        # Items
        items_box = slide.shapes.add_textbox(x_positions[idx], Inches(2), Inches(2.8), Inches(3))
        if_frame = items_box.text_frame
        if_frame.word_wrap = True

        for item in items:
            p = if_frame.add_paragraph() if if_frame.text else if_frame.paragraphs[0]
            p.text = f"• {item}"
            p.font.size = Pt(11)
            p.space_after = Pt(8)

    # Slide 12: Thank You
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    text = slide.shapes.add_textbox(Inches(2), Inches(2.3), Inches(6), Inches(1))
    tf = text.text_frame
    tf.text = "Thank You!"
    p = tf.paragraphs[0]
    p.font.size = Pt(54)
    p.alignment = PP_ALIGN.CENTER
    p.font.color.rgb = Colors.DARK_TEXT

    # Save to bytes
    ppt_buffer = io.BytesIO()
    prs.save(ppt_buffer)
    ppt_buffer.seek(0)

    return ppt_buffer.read()


# Flask route to add to app.py
def add_ppt_routes(app):
    """Add PowerPoint generation routes to Flask app"""

    @app.route('/api/generate-health-check-ppt', methods=['POST'])
    def generate_health_check_ppt():
        """
        Generate PowerPoint directly from workspace data
        No Gem needed - dashboard calls this directly
        """
        try:
            # Get workspace data from audit files
            from pathlib import Path
            DATA_DIR = Path('./audit_data')

            sources_file = DATA_DIR / 'gateway_sources.json'
            destinations_file = DATA_DIR / 'gateway_destinations.json'
            usage_file = DATA_DIR / 'gateway_usage_data.json'

            workspace_data = {
                'workspace_info': {
                    'name': request.json.get('customer_name', 'Customer')
                },
                'sources': json.load(open(sources_file)) if sources_file.exists() else [],
                'destinations': json.load(open(destinations_file)).get('destinations', []) if destinations_file.exists() else [],
                'usage': json.load(open(usage_file)) if usage_file.exists() else {}
            }

            # Generate PowerPoint
            ppt_bytes = generate_ppt_from_data(workspace_data)

            # Send as file download
            customer_name = workspace_data['workspace_info']['name'].replace(' ', '_')
            filename = f"Health_Check_{customer_name}_{datetime.now().strftime('%Y%m%d')}.pptx"

            return send_file(
                io.BytesIO(ppt_bytes),
                mimetype='application/vnd.openxmlformats-officedocument.presentationml.presentation',
                as_attachment=True,
                download_name=filename
            )

        except Exception as e:
            print(f"Error generating PowerPoint: {e}")
            import traceback
            traceback.print_exc()
            return jsonify({'error': str(e)}), 500

    @app.route('/api/generate-ppt-from-gem-code', methods=['POST'])
    def generate_ppt_from_gem_code_route():
        """
        Alternative: Execute Gem-generated Python code server-side
        User pastes Gem code, we run it and return PPT
        """
        try:
            python_code = request.json.get('python_code', '')
            customer_name = request.json.get('customer_name', 'Customer')

            if not python_code:
                return jsonify({'error': 'No Python code provided'}), 400

            # Generate PPT by executing code
            ppt_bytes = generate_ppt_from_gem_code(python_code, customer_name)

            filename = f"Health_Check_{customer_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.pptx"

            return send_file(
                io.BytesIO(ppt_bytes),
                mimetype='application/vnd.openxmlformats-officedocument.presentationml.presentation',
                as_attachment=True,
                download_name=filename
            )

        except Exception as e:
            return jsonify({'error': str(e)}), 500
